package(default_visibility = ["//cauliflowervest"])

exports_files(glob([
    "*.html",
    "*.txt",
]))

filegroup(
    name = "templates",
    data = glob([
        "*.html",
        "*.txt",
    ]),
)
