package(default_visibility = ["//cauliflowervest"])

py_library(
    name = "client",
    srcs = ["client.py"],
    visibility = [
        "//cauliflowervest",
        "//cauliflowervest:cauliflowervest_clients",
    ],
    deps = [
        "//cauliflowervest:settings",
        "//cauliflowervest/client:base_client",
    ],
)
