#ifndef BPOOP_MINI_CHROMIUM_BASE_COMPILER_SPECIFIC_H_
#define BPOOP_MINI_CHROMIUM_BASE_COMPILER_SPECIFIC_H_
#pragma once

#define WARN_UNUSED_RESULT __attribute__((warn_unused_result))

#endif  // BPOOP_MINI_CHROMIUM_BASE_COMPILER_SPECIFIC_H_
